### ISSUE TITLE
Swift3 and Swift2.3 Adaptations

### ISSUE THREAD

**Issue by tiferrei** [nerdishbynature/TanukiKit#13]
Hello @pietbrauer,

I'm a bit confused, I see that you already have a `swift-2.3` branch, however, a lot of it is outdated, like the `Gemfile` dependencies and the pull request `GitLabKit –> TanukiKit` also wasn't implemented.

Would you like me to work on updating this from the master?

Tiago

**Comment by tiferrei** [comment]
Also, I see that `Nocilla` has been removed from that `Cartfile` and is no longer used in the tests, but it is still referenced in Xcode

**Comment by pietbrauer** [comment]
I will rebase it later on, wanted to work on RequestKit first before breaking all other repositories.

**Comment by tiferrei** [comment]
Cool, but `RequestKit` is ready isn't it? Because at least for me everything runs through and the only CI crash I think was just a dependency fault on their side.

**Comment by pietbrauer** [comment]
Yes, but that was the result of my work yesterday. Please be patient.

**Comment by tiferrei** [comment]
Yes, thank you, meanwhile I will work on the `swift-3` version on my fork.

**Comment by pietbrauer** [comment]
Please see #16 and #15

**Comment by sunapi386** [comment]
I'm looking for Swift 3.0 support. It makes sense to close this issue for Swift 2.3, but a separate issue should be created for Swift 3.0 support. I've made it here https://github.com/nerdishbynature/TanukiKit/issues/25.
