### ISSUE TITLE
Support for Swift 3.0

### ISSUE THREAD

**Issue by sunapi386** [nerdishbynature/TanukiKit#25]
This issue should be kept open for folks who are searching for TaunkiKit Swift 3.0 support, until its release.

**Comment by pietbrauer** [comment]
Please see https://github.com/nerdishbynature/TanukiKit/releases/tag/0.4.0 which is the Swift 3.0 release

**Comment by sunapi386** [comment]
Oops, my bad. I glanced and expected a major version bump, like 1.0.0 release.
