### ISSUE TITLE
Login instead of Username?

### ISSUE THREAD

**Issue by tiferrei** [nerdishbynature/TanukiKit#31]
Hello there, I was wondering why the User request [refers to the username](https://github.com/nerdishbynature/TanukiKit/blob/master/TanukiKit/User.swift#L35) as `login` instead of, well, `username`.
Is there a specific conflict with the keyword `username`?

Thanks,
Tiago

**Comment by pietbrauer** [comment]
Mainly consistency across the projects but I am open for Pull Requests to change that.

**Comment by tiferrei** [comment]
Awesome, it would be quite a major change though, maybe release it together with the repo -> projects change, in a major release?

**Comment by pietbrauer** [comment]
Yes, I can hold back this release if you want to make this change.

**Comment by tiferrei** [comment]
Yeah I'm almost done, should have everything in pull requests in 1 week, max.
