### ISSUE TITLE
Error 410

### ISSUE THREAD

**Issue by BaileyJM02** [nerdishbynature/TanukiKit#36]
I get this error when trying to switch from local repos to Gitlab’s via Git2Go

**Comment by pietbrauer** [comment]
Hey, Gitlab decided to remove the API Version TanukiKit is using. Thats why you get a `410` and this is also why I removed Git2Go from Sale.

There is a branch tackling this but it is far from finished. https://github.com/nerdishbynature/TanukiKit/tree/gitlab-v4
