### ISSUE TITLE
Having some difficulty authenticating (401 error)

### ISSUE THREAD

**Issue by tiferrei** [nerdishbynature/TanukiKit#7]
HI there, I am still trying to authenticate to GitLab API, I have tried the method suggested on the instructions:

``` swift
let config = TokenConfiguration("https://code.tiferrei.com/api/v3/", token: "MY-TOKEN")
```

But I immediately get an error saying the function requires the parameter url, and not token. So I tried the following:

``` swift
let config = TokenConfiguration("https://gitlab.example.com/api/v3/", token: "MY-TOKEN")
```

``` swift
let config = TokenConfiguration(url: "https://gitlab.example.com/api/v3/", "MY-TOKEN")
```

``` swift
let config = TokenConfiguration("https://gitlab.example.com/api/v3/", "MY-TOKEN")
```

With these the compiler error got solved, but with a simple `viewDidLoad()` of:

`````` swift
TanukiKit(config).me() { response in
  switch response {
  case .Success(let user):
    print(user.login)
  case .Failure(let error):
    print(error)
  }
}```

I still always get the 401 error on the console.

What am I doing wrong?

Thanks
``````

**Comment by pietbrauer** [comment]
Did you try without `/api/v3/`?

**Comment by tiferrei** [comment]
Only as `https://code.tiferrei.com`? No, I supposed it required the api part as the example. Let me try it...

**Comment by pietbrauer** [comment]
This is what I do in Git2Go when the user is logged in:

``` swift
public static func client() -> TanukiKit {
        if let authToken = privateToken, baseURL = baseURL {
            let apiURL = baseURL.stringByAppendingURLPath("/api/v3")
            let config = PrivateTokenConfiguration(authToken, url: apiURL)
            return TanukiKit(config)
        }
        return TanukiKit()
    }
```

**Comment by tiferrei** [comment]
Hum, without the `/api/v3/` part I now get:

```
Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
```

Guess it's a progress from a 401 hahah

**Comment by pietbrauer** [comment]
You have to use a `PrivateTokenConfiguration` if you are using a self hosted GitLab (authentication is different). See my example.

**Comment by tiferrei** [comment]
Oh, makes sense now! Sorry! Could you please just explain this segment: `if let authToken = privateToken, baseURL = baseURL` what does it do? I mean I understand what if are for but what's the propose of it?

**Comment by pietbrauer** [comment]
It's checking if the things are in the keychain (if the user is logged in) or not.

**Comment by tiferrei** [comment]
Hum, but this one will be permeant, I mean I want it to only ask for auth once and save it to the keychain, then of course, if the user wants to log out, the credential is deleted and the login screen is presented. Do I still need the if condition?

**Comment by pietbrauer** [comment]
Sure, because the keychain entry is optional. It's there for logged in users and its absent for logged out users.

**Comment by tiferrei** [comment]
OK, thanks for the explanation! Closing the issue as solved.
